print("***")
print("STUDENT PROFILE")
print("***")
print("WELCOME TO PYTHON")
print("Name: John Doe")
print("School: ABC University")
print("Department: Computer Science")
print("Favourite food: Rice")
print("Favourite Programming Language: Python")
