Name= input("Enter your name:")
Age= input("Enter your age:")
Department= input("Enter your department:")
Email= input("Enter your email:")
phone_number= input("Enter your phone number:")
school= input("Enter your school:")

print("=========")
print("STUDENT REGISTRATION")
print("=========")
print("welcome", Name)
print("you have successfully registered.")
print("Department:", Department)
print("Email:", Email)
